remote_theme: chrisrhymes/bulma-clean-theme
plugins:
- jekyll-remote-theme # 
title: Software Interview Questions
description: These are possible questions you may encounter when performing a technical interview.
