remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # 
title: Software Interview Questions
description: These are possible questions you may encounter when performing a technical interview.
